# These are supported funding model platforms

github: hyperpolymath
patreon: cc_studio
open_collective: jonathan-jewell
ko_fi: hyperpolymath
tidelift (sonar): # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: hyperpolymath
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: hyperpolymath
polar: # Replace with a single Polar username
buy_me_a_coffee: jonathan.jewell
thanks_dev: https://thanks.dev/dashboard
indieweb: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
