# SPDX-License-Identifier: PMPL-1.0-or-later
[package]
name = "my-dap"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Debug Adapter Protocol implementation for My Language"

[[bin]]
name = "my-dap"
path = "src/main.rs"

[dependencies]
my-lang = { path = "../my-lang" }
serde = { workspace = true }
serde_json.workspace = true
tokio = { workspace = true }
tracing.workspace = true
