# SPDX-License-Identifier: MPL-2.0
name: OSSF Scorecard

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  actions: read
  security-events: write
  id-token: write
  contents: read

jobs:
  scorecard:
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@08586a12bb64b98268fe9ebf552998aa2433a3c2
    permissions:
      contents: read
      security-events: write
      id-token: write
