# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>

name: Secret Scanner
on:
  pull_request:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  scan:
    permissions:
      contents: read
    uses: hyperpolymath/standards/.github/workflows/secret-scanner-reusable.yml@08586a12bb64b98268fe9ebf552998aa2433a3c2
    secrets: inherit
